In [1]:
import requests
import pandas as pd
import time
pd.set_option('max_rows',500)

headers = {'user-agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36'}
url = 'https://c.m.163.com/ug/api/wuhan/app/data/list-total'
r = requests.get(url,headers=headers)

print(len(r.text))

300182

In [2]:
import json
data_json = json.loads(r.text)
data_json.keys()

data = data_json['data']
data.keys()

data_province = data['areaTree'][2]['children'][3]['children']

data_province[0].keys()

dict_keys(['today', 'total', 'extData', 'name', 'id', 'lastUpdateTime', 'children'])

In [3]:
data_province

[{'today': {'confirm': 2,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 1040,
   'suspect': 0,
   'heal': 1000,
   'dead': 0,
   'severe': 0},
  'extData': {},
  'name': '境外输入',
  'id': 'C202006211224112',
  'lastUpdateTime': '2021-06-03 08:51:06',
  'children': []},
 {'today': {'confirm': 15,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 433, 'suspect': 0, 'heal': 376, 'dead': 1, 'severe': 0},
  'extData': {},
  'name': '广州',
  'id': '440100',
  'lastUpdateTime': '2021-06-03 08:51:05',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 423, 'suspect': 0, 'heal': 420, 'dead': 3, 'severe': 0},
  'extData': {},
  'name': '深圳',
  'id': '440300',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 99, 'suspect': 0, 'heal': 98, 'dead': 1, 'severe': 0},
  'extData': {},
  'name': '东莞',
  'id': '441900',
  'lastUpdateTime': '2021-06-03 00:00:52',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 98, 'suspect': 0, 'heal': 97, 'dead': 1, 'severe': 0},
  'extData': {},
  'name': '珠海',
  'id': '440400',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 95, 'suspect': 0, 'heal': 89, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '佛山',
  'id': '440600',
  'lastUpdateTime': '2021-06-03 08:51:05',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 67, 'suspect': 0, 'heal': 67, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '中山',
  'id': '442000',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 62, 'suspect': 0, 'heal': 62, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '惠州',
  'id': '441300',
  'lastUpdateTime': '2021-06-03 00:00:52',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 25, 'suspect': 0, 'heal': 25, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '汕头',
  'id': '440500',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 23, 'suspect': 0, 'heal': 23, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '江门',
  'id': '440700',
  'lastUpdateTime': '2021-06-03 00:00:52',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 22, 'suspect': 0, 'heal': 22, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '湛江',
  'id': '440800',
  'lastUpdateTime': '2021-06-03 00:00:52',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 19, 'suspect': 0, 'heal': 18, 'dead': 1, 'severe': 0},
  'extData': {},
  'name': '肇庆',
  'id': '441200',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 16, 'suspect': 0, 'heal': 16, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '梅州',
  'id': '441400',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 14, 'suspect': 0, 'heal': 14, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '阳江',
  'id': '441700',
  'lastUpdateTime': '2021-06-03 00:00:52',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 14, 'suspect': 0, 'heal': 14, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '茂名',
  'id': '440900',
  'lastUpdateTime': '2021-06-03 00:00:52',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 12, 'suspect': 0, 'heal': 12, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '清远',
  'id': '441800',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 10, 'suspect': 0, 'heal': 9, 'dead': 1, 'severe': 0},
  'extData': {},
  'name': '韶关',
  'id': '440200',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 10, 'suspect': 0, 'heal': 10, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '揭阳',
  'id': '445200',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 6, 'suspect': 0, 'heal': 6, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '汕尾',
  'id': '441500',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 5, 'suspect': 0, 'heal': 5, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '河源',
  'id': '441600',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 5, 'suspect': 0, 'heal': 5, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '潮州',
  'id': '445100',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': 0,
   'dead': 0,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 0, 'suspect': 0, 'heal': 0, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '云浮',
  'id': '445300',
  'lastUpdateTime': '2020-09-13 08:25:22',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': None,
   'dead': None,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 0, 'suspect': 0, 'heal': 0, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '未明确地区',
  'id': '924400',
  'lastUpdateTime': '2021-06-03 00:00:53',
  'children': []},
 {'today': {'confirm': 0,
   'suspect': None,
   'heal': 0,
   'dead': 0,
   'severe': None,
   'storeConfirm': None},
  'total': {'confirm': 0, 'suspect': 0, 'heal': 0, 'dead': 0, 'severe': 0},
  'extData': {},
  'name': '境外输入人员',
  'id': '9532564',
  'lastUpdateTime': '2020-09-13 08:25:22',
  'children': []}]

In [4]:
pd.DataFrame(data_province).head()

,today,total,extData,name,id,lastUpdateTime,children
0,"{'confirm': 2, 'suspect': None, 'heal': None, ...","{'confirm': 1040, 'suspect': 0, 'heal': 1000, ...",{},境外输入,C202006211224112,2021-06-03 08:51:06,[]
1,"{'confirm': 15, 'suspect': None, 'heal': None,...","{'confirm': 433, 'suspect': 0, 'heal': 376, 'd...",{},广州,440100,2021-06-03 08:51:05,[]
2,"{'confirm': 0, 'suspect': None, 'heal': None, ...","{'confirm': 423, 'suspect': 0, 'heal': 420, 'd...",{},深圳,440300,2021-06-03 00:00:53,[]
3,"{'confirm': 0, 'suspect': None, 'heal': None, ...","{'confirm': 99, 'suspect': 0, 'heal': 98, 'dea...",{},东莞,441900,2021-06-03 00:00:52,[]
4,"{'confirm': 0, 'suspect': None, 'heal': None, ...","{'confirm': 98, 'suspect': 0, 'heal': 97, 'dea...",{},珠海,440400,2021-06-03 00:00:53,[]

In [5]:
info = pd.DataFrame(data_province)[['id','lastUpdateTime','name']]
info

                  id       lastUpdateTime    name
0   C202006211224112  2021-06-03 08:51:06    境外输入
1             440100  2021-06-03 08:51:05      广州
2             440300  2021-06-03 00:00:53      深圳
3             441900  2021-06-03 00:00:52      东莞
4             440400  2021-06-03 00:00:53      珠海
5             440600  2021-06-03 08:51:05      佛山
6             442000  2021-06-03 00:00:53      中山
7             441300  2021-06-03 00:00:52      惠州
8             440500  2021-06-03 00:00:53      汕头
9             440700  2021-06-03 00:00:52      江门
10            440800  2021-06-03 00:00:52      湛江
11            441200  2021-06-03 00:00:53      肇庆
12            441400  2021-06-03 00:00:53      梅州
13            441700  2021-06-03 00:00:52      阳江
14            440900  2021-06-03 00:00:52      茂名
15            441800  2021-06-03 00:00:53      清远
16            440200  2021-06-03 00:00:53      韶关
17            445200  2021-06-03 00:00:53      揭阳
18            441500  2021-06-03 00:00:53      汕尾
19            441600  2021-06-03 00:00:53      河源
20            445100  2021-06-03 00:00:53      潮州
21            445300  2020-09-13 08:25:22      云浮
22            924400  2021-06-03 00:00:53   未明确地区
23           9532564  2020-09-13 08:25:22  境外输入人员

In [6]:
today_data = pd.DataFrame([province['today'] for province in data_province])
today_data.head()

   confirm suspect  heal  dead severe storeConfirm
0        2    None   NaN   NaN   None         None
1       15    None   NaN   NaN   None         None
2        0    None   NaN   NaN   None         None
3        0    None   NaN   NaN   None         None
4        0    None   NaN   NaN   None         None

In [7]:
today_data.columns = ['today_'+i for i in today_data.columns]
today_data.head()

,today_confirm,today_suspect,today_heal,today_dead,today_severe,today_storeConfirm
0,2,None,NaN,NaN,None,None
1,15,None,NaN,NaN,None,None
2,0,None,NaN,NaN,None,None
3,0,None,NaN,NaN,None,None
4,0,None,NaN,NaN,None,None

In [8]:
total_data = pd.DataFrame([province['total'] for province in data_province])
total_data.columns = ['total_'+i for i in total_data.columns]
total_data.head()

   total_confirm  total_suspect  total_heal  total_dead  total_severe
0           1040              0        1000           0             0
1            433              0         376           1             0
2            423              0         420           3             0
3             99              0          98           1             0
4             98              0          97           1             0

In [9]:
def get_data(data,info_list):
    info = pd.DataFrame(data)[info_list]#主要信息
    
    today_data = pd.DataFrame([i['today'] for i in data ])
    today_data.columns=['today_'+i for i in today_data.columns]
    
    total_data = pd.DataFrame([i['total'] for i in data])
    total_data.columns = ['total_'+i for i in total_data.columns]
    
    return pd.concat([info,total_data,today_data],axis=1)

In [10]:
today_province = get_data(data_province,['id','lastUpdateTime','name'])
today_province.head()

,id,lastUpdateTime,name,total_confirm,total_suspect,total_heal,total_dead,total_severe,today_confirm,today_suspect,today_heal,today_dead,today_severe,today_storeConfirm
0,C202006211224112,2021-06-03 08:51:06,境外输入,1040,0,1000,0,0,2,None,NaN,NaN,None,None
1,440100,2021-06-03 08:51:05,广州,433,0,376,1,0,15,None,NaN,NaN,None,None
2,440300,2021-06-03 00:00:53,深圳,423,0,420,3,0,0,None,NaN,NaN,None,None
3,441900,2021-06-03 00:00:52,东莞,99,0,98,1,0,0,None,NaN,NaN,None,None
4,440400,2021-06-03 00:00:53,珠海,98,0,97,1,0,0,None,NaN,NaN,None,None

In [11]:
def save_data(data,name):
    file_name = name+'_'+time.strftime('%Y_%m_%d',time.localtime(time.time()))+'.csv'
    data.to_csv(file_name,index=None,encoding='utf_8_sig')
    print(file_name+'保存成功！')

In [12]:
time.strftime('%Y_%m_%d',time.localtime(time.time()))

'2021_06_03'

In [13]:
save_data(today_province,'today_shanghai')

today_shanghai_2021_06_03.csv保存成功！